import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  EN: {
    brandTitle: "SANGASETU",
    brandSubtitle: "Citizen Scheme & Welfare Discovery Portal",
    home: "Home",
    exploreSchemes: "Explore Schemes",
    checkEligibility: "Check Eligibility",
    dashboard: "Dashboard",
    login: "Login",
    register: "Register",
    logout: "Logout",
    calculator: "EMI Calculator",
    partners: "Partner Locator",
    applications: "My Applications",
    profile: "SC Beneficiary Profile",
    heroTitle: "Find Government Schemes You Are Eligible For",
    heroSubtitle: "SANGASETU simplifies welfare discovery across Central and State Governments. Get personalized scheme recommendations based on your age, income, occupation, and SC beneficiary status.",
    findMySchemes: "Find My Schemes",
    exploreAllSchemes: "Explore All Schemes",
    searchPlaceholder: "Search government schemes (e.g., PM KISAN, Ayushman, MUDRA)...",
    featuredTitle: "Featured National Schemes",
    featuredSub: "Popular central and state welfare initiatives empowering millions of citizens.",
    benefits: "Primary Benefit",
    target: "Target Beneficiaries",
    viewDetails: "View Details",
    officialPortal: "Apply on Official Portal",
    checkMyEligibility: "Check My Eligibility",
    locationSetup: "Snapchat Location Radar",
    gpsDetect: "Use Current GPS Location",
    nearbyPartners: "Nearby Bank Branches & CSC Partners",
    disclaimer: "Based on the information provided, you may be eligible.",
    clearFilters: "Clear Filters",
    category: "Category",
    level: "Government Level",
    occupation: "Occupation",
    gender: "Gender",
    sortBy: "Sort By",
    step: "Step",
    nextStep: "Next Step",
    back: "Back",
    calculating: "Evaluating Eligibility...",
    compareSchemes: "Compare Schemes",
    listen: "Listen",
    share: "Share Scheme",
    installApp: "Install App",
    stopAudio: "Stop Audio",
    faqsTitle: "Frequently Asked Questions",
    estimatedAssistance: "Estimated Financial Assistance",
    scBeneficiaryTitle: "Scheduled Caste Beneficiary Info",
    scCategory: "SC Category",
    loanAmount: "Required Loan Amount",
    tenure: "Tenure (Months)",
    moratorium: "Moratorium Period",
    emi: "Monthly EMI",
    totalRepayment: "Total Repayment",
    loading: "Loading data...",
    error: "An error occurred",
    success: "Operation successful",
    retry: "Retry",
    noResults: "No matching schemes found",
    offlineNotice: "You are currently offline",
    connectionRestored: "Connection Restored"
  },
  HI: {
    brandTitle: "संगमसेतु",
    brandSubtitle: "नागरिक कल्याण एवं योजना खोज पोर्टल",
    home: "मुख्य पृष्ठ",
    exploreSchemes: "योजनाएं खोजें",
    checkEligibility: "पात्रता जांचें",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    calculator: "ईएमआई कैलकुलेटर",
    partners: "पार्टनर लोकेटर",
    applications: "मेरे आवेदन",
    profile: "एससी लाभार्थी प्रोफ़ाइल",
    heroTitle: "अपनी पात्रता के अनुसार सरकारी योजनाएं खोजें",
    heroSubtitle: "संगमसेतु केंद्र और राज्य सरकारों की कल्याणकारी योजनाओं की खोज को आसान बनाता है। अपनी आयु, आय, व्यवसाय और अनुसूचित जाति लाभार्थी स्थिति के आधार पर सिफारिशें प्राप्त करें।",
    findMySchemes: "मेरी योजनाएं खोजें",
    exploreAllSchemes: "सभी योजनाएं देखें",
    searchPlaceholder: "सरकारी योजनाएं खोजें (जैसे PM KISAN, आयुष्मान, मुद्रा)...",
    featuredTitle: "प्रमुख राष्ट्रीय योजनाएं",
    featuredSub: "लाखों नागरिकों को सशक्त बनाने वाली लोकप्रिय सरकारी पहल।",
    benefits: "मुख्य लाभ",
    target: "लक्ष्य लाभार्थी",
    viewDetails: "विवरण देखें",
    officialPortal: "आधिकारिक पोर्टल पर आवेदन करें",
    checkMyEligibility: "मेरी पात्रता जांचें",
    locationSetup: "स्थान रडार सेटअप (जीपीएस)",
    gpsDetect: "वर्तमान जीपीएस स्थान का उपयोग करें",
    nearbyPartners: "निकटतम बैंक शाखाएं और सीएससी केंद्र",
    disclaimer: "प्रदान की गई जानकारी के आधार पर, आप पात्र हो सकते हैं।",
    clearFilters: "फ़िल्टर हटाएं",
    category: "श्रेणी",
    level: "सरकारी स्तर",
    occupation: "व्यवसाय",
    gender: "लिंग",
    sortBy: "क्रमानुसार",
    step: "चरण",
    nextStep: "अगला चरण",
    back: "पीछे",
    calculating: "पात्रता का मूल्यांकन किया जा रहा है...",
    compareSchemes: "योजनाओं की तुलना करें",
    listen: "सुनें",
    share: "शेयर करें",
    installApp: "ऐप इंस्टॉल करें",
    stopAudio: "ऑडियो बंद करें",
    faqsTitle: "अक्सर पूछे जाने वाले प्रश्न",
    estimatedAssistance: "अनुमानित वित्तीय सहायता",
    scBeneficiaryTitle: "अनुसूचित जाति लाभार्थी जानकारी",
    scCategory: "एससी श्रेणी",
    loanAmount: "ऋण राशि",
    tenure: "अवधि (महीने)",
    moratorium: "मोरेटोरियम अवधि",
    emi: "मासिक ईएमआई",
    totalRepayment: "कुल भुगतान",
    loading: "डेटा लोड हो रहा है...",
    error: "एक त्रुटि हुई",
    success: "सफल संचालन",
    retry: "पुनः प्रयास करें",
    noResults: "कोई योजना नहीं मिली",
    offlineNotice: "आप ऑफ़लाइन हैं",
    connectionRestored: "कनेक्शन बहाल हो गया"
  },
  TE: {
    brandTitle: "సంగమ్‌సేతు",
    brandSubtitle: "పౌర సంక్షేమ మరియు పథకాల శోధన పోర్టల్",
    home: "హోమ్",
    exploreSchemes: "పథకాలను అన్వేషించండి",
    checkEligibility: "అర్హత తనిఖీ చేయండి",
    dashboard: "డాష్‌బోర్డ్",
    login: "లాగిన్",
    register: "రిజిస్టర్",
    logout: "లాగ్ అవుట్",
    calculator: "EMI క్యాలిక్యులేటర్",
    partners: "భాగస్వామ్య కేంద్రాలు",
    applications: "నా దరఖాస్తులు",
    profile: "SC లబ్ధిదారుల ప్రొఫైల్",
    heroTitle: "మీకు అర్హత ఉన్న ప్రభుత్వ పథకాలను కనుగొనండి",
    heroSubtitle: "సంగమ్‌సేతు కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ సంక్షేమ పథకాలను సులభంగా పొందేలా చేస్తుంది. మీ వయస్సు, ఆదాయం, వృత్తి మరియు SC లబ్ధిదారుల స్థితి ఆధారంగా సలహాలు పొందండి.",
    findMySchemes: "నా పథకాలను కనుగొనండి",
    exploreAllSchemes: "అన్ని పథకాలను చూడండి",
    searchPlaceholder: "ప్రభుత్వ పథకాలను శోధించండి (ఉదా. PM KISAN, ఆయుష్మాన్, ముద్ర)...",
    featuredTitle: "ప్రధాన జాతీయ పథకాలు",
    featuredSub: "లక్షలాది మందికి ఉపయోగపడే ప్రముఖ ప్రభుత్వ సంక్షేమ పథకాలు.",
    benefits: "ముఖ్య ప్రయోజనం",
    target: "లక్ష్య లబ్ధిదారులు",
    viewDetails: "వివరాలు చూడండి",
    officialPortal: "అధికారిక పోర్టల్‌లో దరఖాస్తు చేయండి",
    checkMyEligibility: "నా అర్హత తనిఖీ చేయండి",
    locationSetup: "లొకేషన్ రాడార్ సెటప్ (GPS)",
    gpsDetect: "ప్రస్తుత GPS లొకేషన్ ఉపయోగించండి",
    nearbyPartners: "సమీప బ్యాంక్ శాఖలు & CSC కేంద్రాలు",
    disclaimer: "అందించిన సమాచారం ఆధారంగా, మీరు అర్హులు కావచ్చు.",
    clearFilters: "ఫిల్టర్లు తొలగించండి",
    category: "వర్గం",
    level: "ప్రభుత్వ స్థాయి",
    occupation: "వృత్తి",
    gender: "లింగం",
    sortBy: "క్రమబద్ధీకరించు",
    step: "దశ",
    nextStep: "తదుపరి దశ",
    back: "వెనుకకు",
    calculating: "అర్హత మూల్యాంకనం జరుగుతోంది...",
    compareSchemes: "పథకాలను పోల్చండి",
    listen: "వినండి",
    share: "షేర్ చేయండి",
    installApp: "యాప్ ఇన్స్టాల్ చేయండి",
    stopAudio: "ఆడియో ఆపండి",
    faqsTitle: "తరచుగా అడిగే ప్రశ్నలు",
    estimatedAssistance: "అంచనా వేసిన ఆర్థిక సహాయం",
    scBeneficiaryTitle: "షెడ్యూల్డ్ కులాల లబ్ధిదారుల సమాచారం",
    scCategory: "SC వర్గం",
    loanAmount: "రుణ మొత్తం",
    tenure: "కాలపరిమితి (నెల్లలో)",
    moratorium: "మోరటోరియం కాలం",
    emi: "నెలవారీ EMI",
    totalRepayment: "మొత్తం చెల్లింపు",
    loading: "డేటా లోడ్ అవుతోంది...",
    error: "లోపం సంభవించింది",
    success: "విజయవంతమైంది",
    retry: "మళ్ళీ ప్రయత్నించండి",
    noResults: "పథకాలు ఏవీ కనుగొనబడలేదు",
    offlineNotice: "మీరు ఆఫ్‌లైన్‌లో ఉన్నారు",
    connectionRestored: "కనెక్షన్ పునరుద్ధరించబడింది"
  },
  TA: {
    brandTitle: "சங்கம்சேது",
    brandSubtitle: "அரசு நலத்திட்டங்கள் தேடல் போர்டல்",
    home: "முகப்பு",
    exploreSchemes: "திட்டங்களை ஆராயுங்கள்",
    checkEligibility: "தகுதியை சரிபார்க்கவும்",
    dashboard: "டாஷ்போர்டு",
    login: "லாகின்",
    register: "பதிவு செய்க",
    logout: "லாக்அவுட்",
    calculator: "EMI கணக்கிடு",
    partners: "சேவை மையங்கள்",
    applications: "என் விண்ணப்பங்கள்",
    profile: "SC பயனாளிகள் சுயவிவரம்",
    heroTitle: "நீங்கள் தகுதியான அரசு திட்டங்களைக் கண்டறியவும்",
    heroSubtitle: "மத்திய மற்றும் மாநில அரசு நலத்திட்டங்களை எளிதாகக் கண்டறிய சங்கம்சேது உதவுகிறது.",
    findMySchemes: "எனக்கான திட்டங்களைக் கண்டறி",
    exploreAllSchemes: "அனைத்து திட்டங்களையும் காண்க",
    searchPlaceholder: "அரசு திட்டங்களை தேடுக (PM KISAN, ஆயுஷ்மான்)...",
    featuredTitle: "முக்கிய தேசிய திட்டங்கள்",
    featuredSub: "மில்லியன்கணக்கான குடிமக்களுக்கு உதவும் அரசு நலத்திட்டங்கள்.",
    benefits: "முக்கிய பயன்",
    target: "பயனாளிகள்",
    viewDetails: "விவரங்கள்",
    officialPortal: "அதிகாரப்பூர்வ தளத்தில் விண்ணப்பிக்கவும்",
    checkMyEligibility: "என் தகுதியை சரிபார்",
    locationSetup: "இடம் ராடார் அமைப்பு (GPS)",
    gpsDetect: "தற்போதைய GPS இடத்தை பயன்படுத்து",
    nearbyPartners: "அருகிலுள்ள வங்கி கிளைகள் & CSC மையங்கள்",
    disclaimer: "வழங்கப்பட்ட தகவலின் அடிப்படையில், நீங்கள் தகுதியுடையவராக இருக்கலாம்.",
    clearFilters: "வடிகட்டிகளை நீக்கு",
    category: "பிரிவு",
    level: "அரசு நிலை",
    occupation: "தொழில்",
    gender: "பாலினம்",
    sortBy: "வரிசைப்படுத்து",
    step: "படி",
    nextStep: "அடுத்த படி",
    back: "பின்னால்",
    calculating: "தகுதி கணக்கிடப்படுகிறது...",
    compareSchemes: "திட்டங்களை ஒப்பிடுக",
    listen: "கேளுங்கள்",
    share: "பகிர்க",
    installApp: "ஆப் நிறுவவும்",
    stopAudio: "நிறுத்து",
    faqsTitle: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    estimatedAssistance: "மதிப்பிடப்பட்ட நிதி உதவி",
    scBeneficiaryTitle: "ஆதிதிராவிடர் பயனாளிகள் விவரம்",
    scCategory: "SC பிரிவு",
    loanAmount: "கடன் தொகை",
    tenure: "காலஅளவு (மாதங்கள்)",
    moratorium: "சலுகை காலம்",
    emi: "மாதாந்திர EMI",
    totalRepayment: "மொத்த செலுத்துதல்",
    loading: "தரவு ஏற்றப்படுகிறது...",
    error: "பிழை ஏற்பட்டது",
    success: "வெற்றி",
    retry: "மீண்டும் முயல்க",
    noResults: "திட்டங்கள் எதுவும் இல்லை",
    offlineNotice: "நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்",
    connectionRestored: "இணைப்பு மீட்கப்பட்டது"
  },
  KN: {
    brandTitle: "ಸಂಗಮ್‌ಸೇತು",
    brandSubtitle: "ಸರ್ಕಾರಿ ಯೋಜನೆ ಶೋಧನಾ ಪೋರ್ಟಲ್",
    home: "ಮುಖ್ಯ ಪುಟ",
    exploreSchemes: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    checkEligibility: "ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    logout: "ಲಾಗ್‌ಔಟ್",
    calculator: "EMI ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    partners: "ಪಾಲುದಾರ ಕೇಂದ್ರಗಳು",
    applications: "ನನ್ನ ಅರ್ಜಿಗಳು",
    profile: "SC ಫಲಾನುಭವಿ ಪ್ರೊಫೈಲ್",
    heroTitle: "ನಿಮಗೆ ಅರ್ಹವಿರುವ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ",
    heroSubtitle: "ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರಗಳ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳನ್ನು ಸುಲಭವಾಗಿ ಪಡೆಯಲು ಸಂಗಮ್‌ಸೇತು ನೆರವಾಗುತ್ತದೆ.",
    findMySchemes: "ನನ್ನ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    exploreAllSchemes: "ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    searchPlaceholder: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ (ಉದಾ PM KISAN, ಆಯುಷ್ಮಾನ್)...",
    featuredTitle: "ಪ್ರಮುಖ ರಾಷ್ಟ್ರೀಯ ಯೋಜನೆಗಳು",
    featuredSub: "ಲಕ್ಷಾಂತರ ಜನರಿಗೆ ನೆರವಾಗುವ ಪ್ರಮುಖ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು.",
    benefits: "ಮುಖ್ಯ ಪ್ರಯೋಜನ",
    target: "ಫಲಾನುಭವಿಗಳು",
    viewDetails: "ವಿವರಣೆ ವೀಕ್ಷಿಸಿ",
    officialPortal: "ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    checkMyEligibility: "ನನ್ನ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ",
    locationSetup: "ಸ್ಥಳ ರೇಡಾರ್ ಸೆಟಪ್ (GPS)",
    gpsDetect: "ಪ್ರಸ್ತುತ GPS ಸ್ಥಳ ಬಳಸಿ",
    nearbyPartners: "ಸಮೀಪದ ಬ್ಯಾಂಕ್ ಶಾಖೆಗಳು & CSC ಕೇಂದ್ರಗಳು",
    disclaimer: "ನೀಡಿದ ಮಾಹಿತಿಯ ಆಧಾರದ ಮೇಲೆ, ನೀವು ಅರ್ಹರಾಗಿರಬಹುದು.",
    clearFilters: "ಫಿಲ್ಟರ್ ತೆರವುಗೊಳಿಸಿ",
    category: "ವರ್ಗ",
    level: "ಸರ್ಕಾರಿ ಮಟ್ಟ",
    occupation: "ವೃತ್ತಿ",
    gender: "ಲಿಂಗ",
    sortBy: "ಕ್ರಮಬದ್ಧಗೊಳಿಸಿ",
    step: "ಹಂತ",
    nextStep: "ಮುಂದಿನ ಹಂತ",
    back: "ಹಿಂದಕ್ಕೆ",
    calculating: "ಅರ್ಹತೆ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    compareSchemes: "ಯೋಜನೆಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ",
    listen: "ಆಲಿಸಿ",
    share: "ಹಂಚಿಕೊಳ್ಳಿ",
    installApp: "ಆಪ್ ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿ",
    stopAudio: "ನಿಲ್ಲಿಸಿ",
    faqsTitle: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    estimatedAssistance: "ಅಂದಾಜು ಆರ್ಥಿಕ ನೆರವು",
    scBeneficiaryTitle: "ಪರಿಶಿಷ್ಟ ಜಾತಿ ಫಲಾನುಭವಿ ಮಾಹಿತಿ",
    scCategory: "SC ವರ್ಗ",
    loanAmount: "ಸಾಲದ ಮೊತ್ತ",
    tenure: "ಅವಧಿ (ತಿಂಗಳು)",
    moratorium: "ಮೊರಟೋರಿಯಂ ಅವಧಿ",
    emi: "ಮಾಸಿಕ EMI",
    totalRepayment: "ಒಟ್ಟು ಮರುಪಾವತಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    error: "ದೋಷ ಸಂಭವಿಸಿದೆ",
    success: "ಯಶಸ್ವಿಯಾಗಿದೆ",
    retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
    noResults: "ಯಾವುದೇ ಯೋಜನೆಗಳು ಸಿಗಲಿಲ್ಲ",
    offlineNotice: "ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ",
    connectionRestored: "ಸಂಪರ್ಕ ಮರುಸ್ಥಾಪಿಸಲಾಗಿದೆ"
  },
  ML: {
    brandTitle: "സംഗംസേതു",
    brandSubtitle: "ക്ഷേമ പദ്ധതി ശോധന പോർട്ടൽ",
    home: "ഹോം",
    exploreSchemes: "പദ്ധതികൾ കാണുക",
    checkEligibility: "അർഹത പരിശോധിക്കുക",
    dashboard: "ഡാഷ്ബോർഡ്",
    login: "ലോഗിൻ",
    register: "രജിസ്റ്റർ",
    logout: "ലോഗ്ഔട്ട്",
    calculator: "ഇഎംഐ കാൽക്കുലേറ്റർ",
    partners: "പങ്കാളി കേന്ദ്രങ്ങൾ",
    applications: "എന്റെ അപേക്ഷകൾ",
    profile: "എസ്‌സി ഗുണഭോക്തൃ പ്രൊഫൈൽ",
    heroTitle: "നിങ്ങൾക്ക് അർഹതയുള്ള സർക്കാർ പദ്ധതികൾ കണ്ടെത്തുക",
    heroSubtitle: "കേന്ദ്ര-സംസ്ഥാന സർക്കാരുകളുടെ ക്ഷേമ പദ്ധതികൾ സംഗംസേതു ലളിതമാക്കുന്നു.",
    findMySchemes: "എന്റെ പദ്ധതികൾ കണ്ടെത്തുക",
    exploreAllSchemes: "എല്ലാ പദ്ധതികളും കാണുക",
    searchPlaceholder: "സർക്കാർ പദ്ധതികൾ തിരയുക...",
    featuredTitle: "പ്രധാന ദേശീയ പദ്ധതികൾ",
    featuredSub: "ദശലക്ഷക്കണക്കിന് ജനങ്ങൾക്ക് പ്രയോജനപ്പെടുന്ന ജനക്ഷേമ പദ്ധതികൾ.",
    benefits: "പ്രധാന പ്രയോജനം",
    target: "ഗുണഭോക്താക്കൾ",
    viewDetails: "വിശദാംശങ്ങൾ",
    officialPortal: "ഔദ്യോഗിക പോർട്ടലിൽ അപേക്ഷിക്കുക",
    checkMyEligibility: "എന്റെ അർഹത പരിശോധിക്കുക",
    locationSetup: "ലൊക്കേഷൻ റഡാർ (GPS)",
    gpsDetect: "നിലവിലെ GPS ഉപയോഗിക്കുക",
    nearbyPartners: "സമീപത്തുള്ള ബാങ്ക് ശാഖകളും സിഎസ്സി കേന്ദ്രങ്ങളും",
    disclaimer: "നൽകിയ വിവരങ്ങളുടെ അടിസ്ഥാനത്തിൽ നിങ്ങൾക്ക് അർഹതയുണ്ടായേക്കാം.",
    clearFilters: "ഫിൽട്ടറുകൾ മാറ്റുക",
    category: "വിഭാഗം",
    level: "സർക്കാർ തലം",
    occupation: "തൊഴിൽ",
    gender: "ലിംഗഭേദം",
    sortBy: "ക്രമീകരിക്കുക",
    step: "ഘട്ടം",
    nextStep: "അടുത്ത ഘട്ടം",
    back: "തിരികെ",
    calculating: "അർഹത പരിശോധിക്കുന്നു...",
    compareSchemes: "പദ്ധതികൾ താരതമ്യം ചെയ്യുക",
    listen: "കേൾക്കുക",
    share: "പങ്കുവെക്കുക",
    installApp: "ആപ്പ് ഇൻസ്റ്റാൾ ചെയ്യുക",
    stopAudio: "നിർത്തുക",
    faqsTitle: "ചോദ്യോത്തരങ്ങൾ",
    estimatedAssistance: "പ്രതീക്ഷിക്കുന്ന സാമ്പത്തിക സഹായം",
    scBeneficiaryTitle: "പട്ടികജാതി ഗുണഭോക്തൃ വിവരങ്ങൾ",
    scCategory: "എസ്‌സി വിഭാഗം",
    loanAmount: "വായ്പാ തുക",
    tenure: "കാലാവധി (മാസം)",
    moratorium: "മൊറട്ടോറിയം കാലയളവ്",
    emi: "പ്രതിമാസ EMI",
    totalRepayment: "ആകെ തിരിച്ചടവ്",
    loading: "ഡാറ്റ ലോഡ് ചെയ്യുന്നു...",
    error: "പിശക് സംഭവിച്ചു",
    success: "വിജയം",
    retry: "വീണ്ടും ശ്രമിക്കുക",
    noResults: "പദ്ധതികളൊന്നും കണ്ടെത്തിയില്ല",
    offlineNotice: "നിങ്ങൾ ഓഫ്ലൈനിലാണ്",
    connectionRestored: "കണക്ഷൻ പുനഃസ്ഥാപിച്ചു"
  },
  BN: {
    brandTitle: "সংগমসেতু",
    brandSubtitle: "সরকারি প্রকল্প ও কল্যাণ পোর্টাল",
    home: "হোম",
    exploreSchemes: "প্রকল্প অনুসন্ধান",
    checkEligibility: "যোগ্যতা যাচাই",
    dashboard: "ড্যাশবোর্ড",
    login: "লগইন",
    register: "নিবন্ধন",
    logout: "লগআউট",
    calculator: "ইএমআই ক্যালকুলেটর",
    partners: "পার্টনার সেন্টার",
    applications: "আমার আবেদনপত্র",
    profile: "এসসি সুবিধাভোগী প্রোফাইল",
    heroTitle: "আপনার উপযোগী সরকারি প্রকল্পগুলি খুঁজে নিন",
    heroSubtitle: "সংগমসেতু কেন্দ্র ও রাজ্য সরকারের কল্যাণমূলক প্রকল্পগুলিকে সহজেই খুঁজে পেতে সাহায্য করে।",
    findMySchemes: "আমার জন্য প্রকল্প খুঁজুন",
    exploreAllSchemes: "সমস্ত প্রকল্প দেখুন",
    searchPlaceholder: "সরকারি প্রকল্প খুঁজুন (যেমন PM KISAN, আয়ুষ্মান)...",
    featuredTitle: "প্রধান জাতীয় প্রকল্পসমূহ",
    featuredSub: "লক্ষ লক্ষ নাগরিককে ক্ষমতায়িত করার মতো জনপ্রিয় উদ্যোগ।",
    benefits: "প্রধান সুবিধা",
    target: "লক্ষ্যভিত্তিক সুবিধাভোগী",
    viewDetails: "বিস্তারিত দেখুন",
    officialPortal: "অফিসিয়াল পোর্টালে আবেদন করুন",
    checkMyEligibility: "আমার যোগ্যতা দেখুন",
    locationSetup: "লোকেশন রাডার সেটআপ (GPS)",
    gpsDetect: "বর্তমান GPS অবস্থান ব্যবহার করুন",
    nearbyPartners: "নিকটস্থ ব্যাঙ্ক শাখা ও CSC কেন্দ্র",
    disclaimer: "প্রদত্ত তথ্যের ভিত্তিতে আপনি যোগ্য হতে পারেন।",
    clearFilters: "ফিল্টার মুছুন",
    category: "বিভাগ",
    level: "সরকারি স্তর",
    occupation: "পেশা",
    gender: "লিঙ্গ",
    sortBy: "ক্রমানুসারে",
    step: "ধাপ",
    nextStep: "পরবর্তী ধাপ",
    back: "ফিরে যান",
    calculating: "যোগ্যতা মূল্যায়ন করা হচ্ছে...",
    compareSchemes: "প্রকল্প তুলনা করুন",
    listen: "শুনুন",
    share: "শেয়ার করুন",
    installApp: "অ্যাপ ইনস্টল করুন",
    stopAudio: "বন্ধ করুন",
    faqsTitle: "সাধারণ প্রশ্নাবলী",
    estimatedAssistance: "আনুমানিক আর্থিক সাহায্য",
    scBeneficiaryTitle: "তফসিলি জাতি সুবিধাভোগী তথ্য",
    scCategory: "এসসি বিভাগ",
    loanAmount: "ঋণের পরিমাণ",
    tenure: "মেয়াদ (মাস)",
    moratorium: "মোরেটোরিয়াম সময়সীমা",
    emi: "মাসিক ইএমআই",
    totalRepayment: "মোট পরিশোধ",
    loading: "লোড হচ্ছে...",
    error: "একটি ত্রুটি ঘটেছে",
    success: "সফল হয়েছে",
    retry: "পুনরায় চেষ্টা করুন",
    noResults: "কোন প্রকল্প পাওয়া যায়নি",
    offlineNotice: "আপনি অফলাইনে আছেন",
    connectionRestored: "সংযোগ পুনঃপ্রতিষ্ঠিত হয়েছে"
  },
  MR: {
    brandTitle: "संगमसेतू",
    brandSubtitle: "शासकीय योजना व कल्याण पोर्टल",
    home: "मुख्य पृष्ठ",
    exploreSchemes: "योजना शोधा",
    checkEligibility: "पात्रता तपासा",
    dashboard: "डॅशबोर्ड",
    login: "लॉगिन",
    register: "नोंदणी",
    logout: "लॉगआउट",
    calculator: "ईएमआय कॅल्क्युलेटर",
    partners: "पार्टनर लोकेटर",
    applications: "माझे अर्ज",
    profile: "एससी लाभार्थी प्रोफाइल",
    heroTitle: "तुमच्या पात्रतेनुसार सरकारी योजना शोधा",
    heroSubtitle: "संगमसेतू केंद्र आणि राज्य सरकारच्या कल्याणकारी योजनांचा शोध घेणे सोपे करते।",
    findMySchemes: "माझ्या योजना शोधा",
    exploreAllSchemes: "सर्व योजना पहा",
    searchPlaceholder: "सरकारी योजना शोधा (उदा. PM KISAN, आयुष्यमान)...",
    featuredTitle: "प्रमुख राष्ट्रीय योजना",
    featuredSub: "लाखो नागरिकांना सक्षम करणाऱ्या लोकप्रिय सरकारी योजना।",
    benefits: "मुख्य लाभ",
    target: "लाभार्थी",
    viewDetails: "तपशील पहा",
    officialPortal: "अधिकृत पोर्टलवर अर्ज करा",
    checkMyEligibility: "माझी पात्रता तपासा",
    locationSetup: "स्थान रडार सेटअप (GPS)",
    gpsDetect: "सध्याचे GPS स्थान वापरा",
    nearbyPartners: "जवळपासच्या बँक शाखा आणि CSC केंद्रे",
    disclaimer: "दिलेल्या माहितीच्या आधारे, तुम्ही पात्र असू शकता।",
    clearFilters: "फिल्टर हटवा",
    category: "श्रेणी",
    level: "शासकीय स्तर",
    occupation: "व्यवसाय",
    gender: "लिंग",
    sortBy: "क्रमानुसार",
    step: "टप्पा",
    nextStep: "पुढील टप्पा",
    back: "मागे",
    calculating: "पात्रता मोजली जात आहे...",
    compareSchemes: "योजनांची तुलना करा",
    listen: "ऐका",
    share: "शेअर करा",
    installApp: "अॅप इंस्टॉल करा",
    stopAudio: "थांबवा",
    faqsTitle: "सतत विचारले जाणारे प्रश्न",
    estimatedAssistance: "अंदाजे आर्थिक मदत",
    scBeneficiaryTitle: "अनुसूचित जाती लाभार्थी माहिती",
    scCategory: "एससी वर्ग",
    loanAmount: "कर्ज रक्कम",
    tenure: "कालावधी (महिने)",
    moratorium: "मोरेटोरियम कालावधी",
    emi: "मासिक ईएमआय",
    totalRepayment: "एकूण परतफेड",
    loading: "डेटा लोड होत आहे...",
    error: "त्रुटी आली",
    success: "यशस्वी",
    retry: "पुन्हा प्रयत्न करा",
    noResults: "कोणतीही योजना आढळली नाही",
    offlineNotice: "तुम्ही ऑफलाईन आहात",
    connectionRestored: "कनेक्शन पूर्ववत झाले"
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('sangamsetu_lang') || 'EN');

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
      localStorage.setItem('sangamsetu_lang', newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['EN']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t, availableLanguages: Object.keys(translations), translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
