import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  EN: {
    brandTitle: "SchemeSetu",
    brandSubtitle: "Government Scheme Discovery Portal",
    home: "Home",
    exploreSchemes: "Explore Schemes",
    checkEligibility: "Check Eligibility",
    dashboard: "Dashboard",
    login: "Login",
    register: "Register",
    logout: "Logout",
    heroTitle: "Find Government Schemes You Are Eligible For",
    heroSubtitle: "SchemeSetu simplifies welfare discovery across Central and State Governments. Get personalized scheme recommendations based on your age, income, occupation, and location.",
    findMySchemes: "Find My Schemes",
    exploreAllSchemes: "Explore All Schemes",
    searchPlaceholder: "Search government schemes (e.g., PM KISAN, Ayushman, MUDRA)...",
    featuredTitle: "Featured National Schemes",
    featuredSub: "Popular central and state welfare initiatives empowering millions.",
    benefits: "Primary Benefit",
    target: "Target",
    viewDetails: "Details",
    officialPortal: "Apply on Official Portal",
    checkMyEligibility: "Check My Eligibility",
    locationSetup: "Snapchat Location Setup",
    gpsDetect: "Use Current GPS Location",
    nearbyPartners: "Nearby Service Partners & Bank Branches",
    disclaimer: "Based on the information provided, you may be eligible.",
    clearFilters: "Clear Filters",
    category: "Category",
    level: "Government Level",
    occupation: "Occupation",
    gender: "Gender",
    sortBy: "Sort By",
    step: "Step",
    nextStep: "Next Step",
    back: "Back",
    calculating: "Evaluating Eligibility..."
  },
  HI: {
    brandTitle: "स्कीमसेतु",
    brandSubtitle: "सरकारी योजना खोज पोर्टल",
    home: "मुख्य पृष्ठ",
    exploreSchemes: "योजनाएं खोजें",
    checkEligibility: "पात्रता जांचें",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    heroTitle: "अपनी पात्रता के अनुसार सरकारी योजनाएं खोजें",
    heroSubtitle: "स्कीमसेतु केंद्र और राज्य सरकारों की कल्याणकारी योजनाओं की खोज को आसान बनाता है। अपनी आयु, आय, व्यवसाय और स्थान के आधार पर व्यक्तिगत सिफारिशें प्राप्त करें।",
    findMySchemes: "मेरी योजनाएं खोजें",
    exploreAllSchemes: "सभी योजनाएं देखें",
    searchPlaceholder: "सरकारी योजनाएं खोजें (जैसे PM KISAN, आयुष्मान, मुद्रा)...",
    featuredTitle: "प्रमुख राष्ट्रीय योजनाएं",
    featuredSub: "लाखों नागरिकों को सशक्त बनाने वाली लोकप्रिय सरकारी पहल।",
    benefits: "मुख्य लाभ",
    target: "लक्ष्य लाभार्थी",
    viewDetails: "विवरण देखें",
    officialPortal: "आधिकारिक पोर्टल पर आवेदन करें",
    checkMyEligibility: "मेरी पात्रता जांचें",
    locationSetup: "स्थान सेटअप (मैप / जीपीएस)",
    gpsDetect: "वर्तमान जीपीएस स्थान का उपयोग करें",
    nearbyPartners: "निकटतम बैंक शाखाएं और सीएससी केंद्र",
    disclaimer: "प्रदान की गई जानकारी के आधार पर, आप पात्र हो सकते हैं।",
    clearFilters: "फ़िल्टर हटाएं",
    category: "श्रेणी",
    level: "सरकारी स्तर",
    occupation: "व्यवसाय",
    gender: "लिंग",
    sortBy: "क्रमानुसार",
    step: "चरण",
    nextStep: "अगला चरण",
    back: "पीछे",
    calculating: "पात्रता का मूल्यांकन किया जा रहा है..."
  },
  TE: {
    brandTitle: "స్కీమ్‌సేతు",
    brandSubtitle: "ప్రభుత్వ పథకాల శోధన పోర్టల్",
    home: "హోమ్",
    exploreSchemes: "పథకాలను అన్వేషించండి",
    checkEligibility: "అర్హత తనిఖీ చేయండి",
    dashboard: "డాష్‌బోర్డ్",
    login: "లాగిన్",
    register: "రిజిస్టర్",
    logout: "లాగ్ అవుట్",
    heroTitle: "మీకు అర్హత ఉన్న ప్రభుత్వ పథకాలను కనుగొనండి",
    heroSubtitle: "స్కీమ్‌సేతు కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ సంక్షేమ పథకాలను సులభంగా పొందేలా చేస్తుంది. మీ వయస్సు, ఆదాయం, వృత్తి మరియు ప్రదేశం ఆధారంగా సలహాలు పొందండి.",
    findMySchemes: "నా పథకాలను కనుగొనండి",
    exploreAllSchemes: "అన్ని పథకాలను చూడండి",
    searchPlaceholder: "ప్రభుత్వ పథకాలను శోధించండి (ఉదా. PM KISAN, ఆయుష్మాన్, ముద్ర)...",
    featuredTitle: "ప్రధాన జాతీయ పథకాలు",
    featuredSub: "లక్షలాది మందికి ఉపయోగపడే ప్రముఖ ప్రభుత్వ సంక్షేమ పథకాలు.",
    benefits: "ముఖ్య ప్రయోజనం",
    target: "లక్ష్య లబ్ధిదారులు",
    viewDetails: "వివరాలు చూడండి",
    officialPortal: "అధికారిక పోర్టల్‌లో దరఖాస్తు చేయండి",
    checkMyEligibility: "నా అర్హత తనిఖీ చేయండి",
    locationSetup: "స్నాప్‌చాట్ లొకేషన్ సెటప్ (మ్యాప్ / GPS)",
    gpsDetect: "ప్రస్తుత GPS లొకేషన్ ఉపయోగించండి",
    nearbyPartners: "సమీప బ్యాంక్ శాఖలు & CSC కేంద్రాలు",
    disclaimer: "అందించిన సమాచారం ఆధారంగా, మీరు అర్హులు కావచ్చు.",
    clearFilters: "ఫిల్టర్లు తొలగించండి",
    category: "వర్గం",
    level: "ప్రభుత్వ స్థాయి",
    occupation: "వృత్తి",
    gender: "లింగం",
    sortBy: "క్రమబద్ధీకరించు",
    step: "దశ",
    nextStep: "తదుపరి దశ",
    back: "వెనుకకు",
    calculating: "అర్హత మూల్యాంకనం జరుగుతోంది..."
  },
  TA: {
    brandTitle: "ஸ்கீம்சேது",
    brandSubtitle: "அரசு திட்டங்கள் தேடல் போர்டல்",
    home: "முகப்பு",
    exploreSchemes: "திட்டங்களை ஆராயுங்கள்",
    checkEligibility: "தகுதியை சரிபார்க்கவும்",
    dashboard: "டாஷ்போர்டு",
    login: "லாகின்",
    register: "பதிவு செய்க",
    logout: "லாக்அவுட்",
    heroTitle: "நீங்கள் தகுதியான அரசு திட்டங்களைக் கண்டறியவும்",
    heroSubtitle: "மத்திய மற்றும் மாநில அரசு நலத்திட்டங்களை எளிதாகக் கண்டறிய ஸ்கீம்சேது உதவுகிறது.",
    findMySchemes: "எனக்கான திட்டங்களைக் கண்டறி",
    exploreAllSchemes: "அனைத்து திட்டங்களையும் காண்க",
    searchPlaceholder: "அரசு திட்டங்களை தேடுக (PM KISAN, ஆயுஷ்மான்)...",
    featuredTitle: "முக்கிய தேசிய திட்டங்கள்",
    featuredSub: "மில்லியன்கணக்கான குடிமக்களுக்கு உதவும் அரசு நலத்திட்டங்கள்.",
    benefits: "முக்கிய பயன்",
    target: "பயனாளிகள்",
    viewDetails: "விவரங்கள்",
    officialPortal: "அதிகாரப்பூர்வ தளத்தில் விண்ணப்பிக்கவும்",
    checkMyEligibility: "என் தகுதியை சரிபார்",
    locationSetup: "இடம் அமைப்பு (GPS / மேப்)",
    gpsDetect: "தற்போதைய GPS இடத்தை பயன்படுத்து",
    nearbyPartners: "அருகிலுள்ள வங்கி கிளைகள் & CSC மையங்கள்",
    disclaimer: "வழங்கப்பட்ட தகவலின் அடிப்படையில், நீங்கள் தகுதியுடையவராக இருக்கலாம்.",
    clearFilters: "வடிகட்டிகளை நீக்கு",
    category: "பிரிவு",
    level: "அரசு நிலை",
    occupation: "தொழில்",
    gender: "பாலினம்",
    sortBy: "வரிசைப்படுத்து",
    step: "படி",
    nextStep: "அடுத்த படி",
    back: "பின்னால்",
    calculating: "தகுதி கணக்கிடப்படுகிறது..."
  },
  KN: {
    brandTitle: "స్కీమ్‌సేతు",
    brandSubtitle: "ಸರ್ಕಾರಿ ಯೋಜನೆ ಶೋಧನಾ ಪೋರ್ಟಲ್",
    home: "ಮುಖ್ಯ ಪುಟ",
    exploreSchemes: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    checkEligibility: "ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    logout: "ಲಾಗ್‌ಔಟ್",
    heroTitle: "ನಿಮಗೆ ಅರ್ಹವಿರುವ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ",
    heroSubtitle: "ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರಗಳ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳನ್ನು ಸುಲಭವಾಗಿ ಪಡೆಯಲು ಸ್ಕೀಮ್‌ಸೇತು ನೆರವಾಗುತ್ತದೆ.",
    findMySchemes: "ನನ್ನ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    exploreAllSchemes: "ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    searchPlaceholder: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ (ಉದಾ PM KISAN, ಆಯುಷ್ಮಾನ್)...",
    featuredTitle: "ಪ್ರಮುಖ ರಾಷ್ಟ್ರೀಯ ಯೋಜನೆಗಳು",
    featuredSub: "ಲಕ್ಷಾಂತರ ಜನರಿಗೆ ನೆರವಾಗುವ ಪ್ರಮುಖ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು.",
    benefits: "ಮುಖ್ಯ ಪ್ರಯೋಜನ",
    target: "ಫಲಾನುಭವಿಗಳು",
    viewDetails: "ವಿವರಣೆ ವೀಕ್ಷಿಸಿ",
    officialPortal: "ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    checkMyEligibility: "ನನ್ನ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ",
    locationSetup: "ಸ್ಥಳ ಸೆಟಪ್ (ಮ್ಯಾಪ್ / GPS)",
    gpsDetect: "ಪ್ರಸ್ತುತ GPS ಸ್ಥಳ ಬಳಸಿ",
    nearbyPartners: "ಸಮೀಪದ ಬ್ಯಾಂಕ್ ಶಾಖೆಗಳು & CSC ಕೇಂದ್ರಗಳು",
    disclaimer: "ನೀಡಿದ ಮಾಹಿತಿಯ ಆಧಾರದ ಮೇಲೆ, ನೀವು ಅರ್ಹರಾಗಿರಬಹುದು.",
    clearFilters: "ಫಿಲ್ಟರ್ ತೆರವುಗೊಳಿಸಿ",
    category: "ವರ್ಗ",
    level: "ಸರ್ಕಾರಿ ಮಟ್ಟ",
    occupation: "ವೃತ್ತಿ",
    gender: "ಲಿಂಗ",
    sortBy: "ಕ್ರಮಬದ್ಧಗೊಳಿಸಿ",
    step: "ಹಂತ",
    nextStep: "ಮುಂದಿನ ಹಂತ",
    back: "ಹಿಂದಕ್ಕೆ",
    calculating: "ಅರ್ಹತೆ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗುತ್ತಿದೆ..."
  },
  MR: {
    brandTitle: "स्कीमसेतू",
    brandSubtitle: "शासकीय योजना शोध पोर्टल",
    home: "मुख्य पृष्ठ",
    exploreSchemes: "योजना शोधा",
    checkEligibility: "पात्रता तपासा",
    dashboard: "डॅशबोर्ड",
    login: "लॉगिन",
    register: "नोंदणी",
    logout: "लॉगआउट",
    heroTitle: "तुमच्या पात्रतेनुसार सरकारी योजना शोधा",
    heroSubtitle: "स्कीमसेतू केंद्र आणि राज्य सरकारच्या कल्याणकारी योजनांचा शोध घेणे सोपे करते.",
    findMySchemes: "माझ्या योजना शोधा",
    exploreAllSchemes: "सर्व योजना पहा",
    searchPlaceholder: "सरकारी योजना शोधा (उदा. PM KISAN, आयुष्यमान)...",
    featuredTitle: "प्रमुख राष्ट्रीय योजना",
    featuredSub: "लाखो नागरिकांना सक्षम करणाऱ्या लोकप्रिय सरकारी योजना.",
    benefits: "मुख्य लाभ",
    target: "लाभार्थी",
    viewDetails: "तपशील पहा",
    officialPortal: "अधिकृत पोर्टलवर अर्ज करा",
    checkMyEligibility: "माझी पात्रता तपासा",
    locationSetup: "स्थान सेटअप (GPS / मॅप)",
    gpsDetect: "सध्याचे GPS स्थान वापरा",
    nearbyPartners: "जवळपासच्या बँक शाखा आणि CSC केंद्रे",
    disclaimer: "दिलेल्या माहितीच्या आधारे, तुम्ही पात्र असू शकता.",
    clearFilters: "फिल्टर हटवा",
    category: "श्रेणी",
    level: "शासकीय स्तर",
    occupation: "व्यवसाय",
    gender: "लिंग",
    sortBy: "क्रमानुसार",
    step: "टप्पा",
    nextStep: "पुढील टप्पा",
    back: "मागे",
    calculating: "पात्रता मोजली जात आहे..."
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('schemesetu_lang') || 'EN');

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
      localStorage.setItem('schemesetu_lang', newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['EN']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t, availableLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
