import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  // Multi-lingual dictionary
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'onboarding_title_1': 'Dashboard Overview',
      'onboarding_subtitle_1':
          'View your collection efficiency, pending dues, and auction statuses at a glance.',
      'onboarding_title_2': 'Automated Messaging',
      'onboarding_subtitle_2':
          'Send payment receipts and overdue reminders automatically via WhatsApp.',
      'onboarding_title_3': 'Multi-Language Support',
      'onboarding_subtitle_3':
          'Tap the translate icon to instantly change the app language to your preference.',
      'onboarding_title_4': 'Stay Notified',
      'onboarding_subtitle_4':
          'Tap the bell icon to enable local notifications and never miss a payment update.',
      'skip': 'Skip',
      'next': 'Next',
      'get_started': 'Get Started',
      'app_title': 'SanghaSetu',
      'login_title': 'Fintech Chit Fund',
      'enter_phone': 'Enter Mobile Number',
      'send_otp': 'Send OTP',
      'verify_otp': 'Verify OTP',
      'enter_otp': 'Enter 6-digit OTP',
      'enter_pin': 'Enter 4-Digit Secure PIN',
      'setup_pin': 'Setup 4-Digit Secure PIN',
      'confirm_pin': 'Confirm your PIN',
      'pin_error': 'Incorrect PIN, try again',
      'biometric_login': 'Fingerprint Login',
      'forgot_pin': 'Forgot PIN?',
      'reset_pin': 'Reset Secure PIN',
      'login_btn': 'Log In',
      'save_btn': 'Save',
      'cancel_btn': 'Cancel',

      // Dashboard
      'dashboard': 'Dashboard',
      'total_groups': 'Total Groups',
      'total_members': 'Total Members',
      'monthly_collection': 'Month Collection',
      'pending_amount': 'Pending Amount',
      'pending_members': 'Pending Members',
      'quick_actions': 'Quick Actions',
      'add_group': 'Add Group',
      'add_member': 'Add Member',
      'target': 'Target',
      'collected_label': 'collected',
      'groups_cash_overview': 'Groups & Cash Overview',
      'expected': 'Expected',
      'collected': 'Collected',
      'pending': 'Pending',
      'chit_groups': 'Chit Groups',
      'member_names': 'Member Names',
      'member_names_hint': 'One per line: Name, Mobile (optional)',
      'choose_date': 'Choose Date',
      'no_groups_configured': 'No groups configured yet.',
      'create_first_group': 'Create Your First Group',
      'started': 'Started',
      'members': 'Members',
      'monthly': 'Monthly',
      'duration': 'Duration',
      'months': 'Months',
      'sync': 'Sync',
      'edit': 'Edit',
      'delete': 'Delete',
      'pending_list': 'Pending List',
      'monthly_report': 'Monthly Report',
      'settings': 'Settings',
      'recent_activity': 'Recent Activity',
      'view_all': 'View All',
      'no_activity_yet':
          'No activity yet. Add a group, members, and payments to start tracking.',
      'pending_dues': 'Pending Dues',
      'all_dues_collected': 'All dues collected for this month! 🎉',
      'overdue': 'Overdue',

      // Group Screen
      'group_name': 'Group Name',
      'installment_amt': 'Monthly Installment',
      'duration_months': 'Duration (Months)',
      'start_date': 'Start Date',
      'create_group_btn': 'Create Group',
      'group_list': 'Active Groups',

      // Member Screen
      'member_name': 'Member Name',
      'father_name': 'Father Name',
      'mobile_number': 'Mobile Number',
      'address': 'Residential Address',
      'aadhaar_optional': 'Aadhaar Number (Optional)',
      'profile_photo': 'Profile Photo',
      'select_group': 'Select Group',
      'register_member_btn': 'Register Member',
      'members_list': 'Members List',
      'member_profile': 'Member Profile',
      'total_paid': 'Total Paid',
      'pending_bal': 'Pending',
      'enrolled_groups': 'Enrolled Groups',
      'not_enrolled': 'Not enrolled in any group.',
      'months_unit': 'months',
      'month_unit': 'month',

      // Payment Screen
      'payments_tracker': 'Payments Tracker',
      'paid_status': 'PAID',
      'pending_status': 'PENDING',
      'toggle_payment': 'Tap to Toggle Payment',
      'installment_history': 'Installment History',

      // Winner Screen
      'winner_module': 'Auction Winners',
      'declare_winner': 'Declare Month Winner',
      'win_amount': 'Winning Bid Amount',
      'select_winner': 'Select Winner Member',
      'winner_date': 'Winner Date',
      'winner_history': 'Winners History',
      'bid_amount': 'Bid Amount',

      // Pending List Screen
      'due_amount': 'Due Amount',
      'call_reminder': 'Call Member',
      'whatsapp_reminder': 'WhatsApp Reminder',

      // Settings Screen
      'dark_theme': 'Dark Theme',
      'light_theme': 'Light Theme',
      'language': 'Language / زبان / తెలుగు',
      'backup_restore': 'Backup & Restore',
      'manual_backup': 'Export JSON Backup',
      'google_drive_backup': 'Google Drive Backup',
      'auto_local_backup': 'Auto Local Backup',
      'restore_backup': 'Import & Restore Backup',
      'backup_copied_clipboard': 'Backup copied to clipboard!',
      'import_backup_title': 'Import Backup',
      'import_backup_hint': 'Paste backup JSON here...',
      'unable_to_open': 'Unable to open link.',
      'theme_description': 'Toggle app appearance',
      'biometric_description': 'Use fingerprint to unlock',
      'privacy_policy': 'Privacy Policy',
      'about_app': 'About App',
      'google_translate': 'Google Translate',
      'restore': 'Restore',
      'backup_success': 'Backup executed successfully!',
      'restore_success': 'Database restored successfully!',
      'restore_fail': 'Restoration failed. Verify JSON.',
      'auction_paid': 'Auction Paid',
      'auction_left': 'Auction Left',
      'foreman_commission': 'Foreman Commission',
      'dividends_distributed': 'Dividends Distributed',
      'payment_mode_cash': 'Cash',
      'payment_mode_upi': 'UPI',
      'payment_mode_bank': 'Bank Transfer',
      'payment_mode_transfer': 'Transfer',
      'send_receipt': 'Send Receipt',
      'transfer_installment': 'Transfer Installment',
      'transfer_from': 'Transfer from',
      'transfer_to': 'Transfer to',
      'mark_as_paid': 'Mark as Paid',
      'remind_pending': 'Remind Pending Members',
    },
    'ur': {
      'onboarding_title_1': 'ڈیش بورڈ کا جائزہ',
      'onboarding_subtitle_1':
          'اپنی جمع کرنے کی کارکردگی، واجب الادا رقم، اور نیلامی کے حالات ایک نظر میں دیکھیں۔',
      'onboarding_title_2': 'خودکار پیغامات',
      'onboarding_subtitle_2':
          'ادائیگی کی رسیدیں اور واجب الادا یاد دہانیاں واٹس ایپ کے ذریعے خودکار طور پر بھیجیں۔',
      'onboarding_title_3': 'کثیر لسانی سپورٹ',
      'onboarding_subtitle_3':
          'اپنی پسند کے مطابق ایپ کی زبان کو فوری طور پر تبدیل کرنے کے لیے ترجمہ آئیکن پر ٹیپ کریں۔',
      'onboarding_title_4': 'باخبر رہیں',
      'onboarding_subtitle_4':
          'مقامی اطلاعات کو فعال کرنے کے لیے گھنٹی کے آئیکن پر ٹیپ کریں اور کبھی بھی ادائیگی کی اپ ڈیٹ مت چھوڑیں۔',
      'skip': 'چھوڑیں',
      'next': 'اگلا',
      'get_started': 'شروع کریں',
      'app_title': 'SanghaSetu',
      'login_title': 'فن ٹیک چِٹ فنڈ',
      'enter_phone': 'موبائل نمبر درج کریں',
      'send_otp': 'او ٹی پی بھیجیں',
      'verify_otp': 'او ٹی پی کی تصدیق کریں',
      'enter_otp': '6 ہندسوں کا او ٹی پی درج کریں',
      'enter_pin': '4 ہندسوں کا پن درج کریں',
      'setup_pin': '4 ہندسوں کا پن سیٹ کریں',
      'confirm_pin': 'پن کی تصدیق کریں',
      'pin_error': 'غلط پن، دوبارہ کوشش کریں',
      'biometric_login': 'فنگر پرنٹ لاگ ان',
      'forgot_pin': 'پن بھول گئے؟',
      'reset_pin': 'پن دوبارہ ترتیب دیں',
      'login_btn': 'لاگ ان کریں',
      'save_btn': 'محفوظ کریں',
      'cancel_btn': 'منسوخ کریں',

      // Dashboard
      'dashboard': 'ڈیش بورڈ',
      'total_groups': 'کل گروپس',
      'total_members': 'کل ممبران',
      'monthly_collection': 'ماہانہ وصولی',
      'pending_amount': 'باقی رقم',
      'pending_members': 'باقی ممبران',
      'quick_actions': 'فوری اقدامات',
      'add_group': 'گروپ شامل کریں',
      'add_member': 'ممبر شامل کریں',
      'target': 'ٹارگٹ',
      'collected_label': 'جمع شدہ',
      'groups_cash_overview': 'گروپس اور کیش کا جائزہ',
      'expected': 'متوقع',
      'collected': 'جمع شدہ',
      'pending': 'بقایا',
      'chit_groups': 'چٹ گروپس',
      'member_names': 'ممبران کے نام',
      'member_names_hint': 'ایک فی لائن: نام، موبائل (اختیاری)',
      'choose_date': 'تاریخ منتخب کریں',
      'no_groups_configured': 'ابھی تک کوئی گروپ ترتیب نہیں دیا گیا۔',
      'create_first_group': 'اپنا پہلا گروپ بنائیں',
      'started': 'شروع ہوا',
      'members': 'ممبران',
      'monthly': 'ماہانہ',
      'duration': 'مدت',
      'months': 'مہینے',
      'sync': 'ہم آہنگ کریں',
      'edit': 'ترمیم کریں',
      'delete': 'حذف کریں',
      'pending_list': 'باقی فہرست',
      'monthly_report': 'ماہانہ رپورٹ',
      'settings': 'ترتیبات',
      'recent_activity': 'حالیہ سرگرمی',
      'view_all': 'سب دیکھیں',
      'no_activity_yet':
          'ابھی تک کوئی سرگرمی نہیں۔ ٹریکنگ شروع کرنے کے لیے گروپ اور ممبران شامل کریں۔',
      'pending_dues': 'باقی واجبات',
      'all_dues_collected': 'اس مہینے کے تمام واجبات جمع ہو گئے ہیں! 🎉',
      'overdue': 'تاخیر شدہ',

      // Group Screen
      'group_name': 'گروپ کا نام',
      'installment_amt': 'ماہانہ قسط',
      'duration_months': 'مدت (مہینے)',
      'start_date': 'شروع ہونے کی تاریخ',
      'create_group_btn': 'گروپ بنائیں',
      'group_list': 'فعال گروپس',

      // Member Screen
      'member_name': 'ممبر کا نام',
      'father_name': 'والد کا نام',
      'mobile_number': 'موبائل نمبر',
      'address': 'رہائشی پتہ',
      'aadhaar_optional': 'آدھار نمبر (اختیاری)',
      'profile_photo': 'پروفائل تصویر',
      'select_group': 'گروپ منتخب کریں',
      'register_member_btn': 'ممبر رجسٹر کریں',
      'members_list': 'ممبران کی فہرست',
      'member_profile': 'ممبر پروفائل',
      'total_paid': 'کل ادا شدہ',
      'pending_bal': 'بकाया',
      'enrolled_groups': 'شامل کردہ گروپ',
      'not_enrolled': 'کسی گروپ میں شامل نہیں ہے۔',
      'months_unit': 'مہینے',
      'month_unit': 'مہینہ',

      // Payment Screen
      'payments_tracker': 'ادائیگی ٹریکر',
      'paid_status': 'ادا شدہ',
      'pending_status': 'باقی ہے',
      'toggle_payment': 'ادائیگی تبدیل کرنے کے لیے تھپتھپائیں',
      'installment_history': 'قسط کی تاریخ',

      // Winner Screen
      'winner_module': 'نیلامی کے فاتحین',
      'declare_winner': 'ماہانہ فاتح کا اعلان کریں',
      'win_amount': 'فاتح بولی کی رقم',
      'select_winner': 'فاتح ممبر منتخب کریں',
      'winner_date': 'جیتنے کی تاریخ',
      'winner_history': 'فاتحین کی تاریخ',
      'bid_amount': 'بولی کی رقم',

      // Pending List Screen
      'due_amount': 'باقی رقم',
      'call_reminder': 'کال کریں',
      'whatsapp_reminder': 'واٹس ایپ یاددہانی',

      // Settings Screen
      'dark_theme': 'ڈارک تھیم',
      'light_theme': 'لائٹ تھیم',
      'language': 'زبان / Language / తెలుగు',
      'backup_restore': 'بیک اپ اور بحالی',
      'manual_backup': 'بیک اپ ایکسپورٹ کریں',
      'google_drive_backup': 'گوگل ڈرائیو بیک اپ',
      'auto_local_backup': 'خودکار مقامی بیک اپ',
      'restore_backup': 'بیک اپ بحال کریں',
      'backup_copied_clipboard': 'بیک اپ کلپ بورڈ پر کاپی ہو گیا ہے!',
      'import_backup_title': 'بیک اپ درآمد کریں',
      'import_backup_hint': 'یہاں بیک اپ JSON پیسٹ کریں...',
      'unable_to_open': 'لنک کھولنے میں مسئلہ ہوا۔',
      'theme_description': 'ایپ کی ظاہری شکل تبدیل کریں',
      'biometric_description': 'کھولنے کے لیے فنگر پرنٹ استعمال کریں',
      'privacy_policy': 'رازداری کی پالیسی',
      'about_app': 'ایپ کے بارے میں',
      'google_translate': 'گوگل ٹرانسلیٹ',
      'restore': 'بحال کریں',
      'backup_success': 'بیک اپ کامیابی سے مکمل ہو گیا!',
      'restore_success': 'ڈیٹا بیس کامیابی سے بحال ہو گیا!',
      'restore_fail': 'بحالی ناکام ہو گئی۔ ڈیٹا چیک کریں۔',
      'auction_paid': 'نیلامی ادا شدہ',
      'auction_left': 'نیلامی باقی',
      'foreman_commission': 'فورمین کمیشن',
      'dividends_distributed': 'منافع تقسیم کیا گیا',
      'payment_mode_cash': 'نقد',
      'payment_mode_upi': 'یو پی آئی',
      'payment_mode_bank': 'بینک ٹرانسفر',
      'payment_mode_transfer': 'منتقل',
      'send_receipt': 'رسید بھیجیں',
      'transfer_installment': 'قسط منتقل کریں',
      'transfer_from': 'سے منتقل کریں',
      'transfer_to': 'کو منتقل کریں',
      'mark_as_paid': 'ادا شدہ کے طور پر نشان زد کریں',
      'remind_pending': 'باقیہ ممبران کو یاد دلائیں',
    },
    'te': {
      'onboarding_title_1': 'డాష్‌బోర్డ్ అవలోకనం',
      'onboarding_subtitle_1':
          'మీ వసూళ్ల సామర్థ్యం, బకాయిలు మరియు వేలం స్థితిగతులను ఒకే చూపులో చూడండి.',
      'onboarding_title_2': 'ఆటోమేటెడ్ సందేశాలు',
      'onboarding_subtitle_2':
          'వాట్సాప్ ద్వారా చెల్లింపు రశీదులు మరియు బకాయిల రిమైండర్‌లను ఆటోమేటిక్‌గా పంపండి.',
      'onboarding_title_3': 'బహుభాషా మద్దతు',
      'onboarding_subtitle_3':
          'యాప్ భాషను మీ ప్రాధాన్యతకు తక్షణమే మార్చడానికి అనువాద చిహ్నాన్ని నొక్కండి.',
      'onboarding_title_4': 'అప్‌డేట్ పొందండి',
      'onboarding_subtitle_4':
          'స్థానిక నోటిఫికేషన్‌లను ప్రారంభించడానికి గంట చిహ్నాన్ని నొక్కండి మరియు చెల్లింపు అప్‌డేట్‌లను ఎప్పటికీ కోల్పోకండి.',
      'skip': 'దాటవేయి',
      'next': 'తరువాత',
      'get_started': 'ప్రారంభించండి',
      'app_title': 'SanghaSetu',
      'login_title': 'ఫిన్‌టెక్ చిట్ ఫండ్',
      'enter_phone': 'మొబైల్ సంఖ్యను నమోదు చేయండి',
      'send_otp': 'OTP పంపండి',
      'verify_otp': 'OTP ని ధృవీకరించండి',
      'enter_otp': '6-అంకెల OTP ని నమోదు చేయండి',
      'enter_pin': '4-అంకెల పిన్ నమోదు చేయండి',
      'setup_pin': '4-అంకెల పిన్ సెటప్ చేయండి',
      'confirm_pin': 'పిన్ నిర్ధారించండి',
      'pin_error': 'తప్పు పిన్, మళ్ళీ ప్రయత్నించండి',
      'biometric_login': 'వేలిముద్ర లాగిన్',
      'forgot_pin': 'పిన్ మరిచిపోయారా?',
      'reset_pin': 'పిన్ రీసెట్ చేయండి',
      'login_btn': 'లాగిన్ అవ్వండి',
      'save_btn': 'సేవ్ చేయండి',
      'cancel_btn': 'రద్దు చేయండి',

      // Dashboard
      'dashboard': 'డ్యాష్‌బోర్డ్',
      'total_groups': 'మొత్తం గ్రూపులు',
      'total_members': 'మొత్తం సభ్యులు',
      'monthly_collection': 'నెలవారీ వసూలు',
      'pending_amount': 'బకాయి మొత్తం',
      'pending_members': 'బకాయి సభ్యులు',
      'quick_actions': 'త్వరిత చర్యలు',
      'add_group': 'గ్రూప్ జోడించు',
      'add_member': 'సభ్యుడిని జోడించు',
      'target': 'లక్ష్యం',
      'collected_label': 'వసూలు చేయబడింది',
      'groups_cash_overview': 'గ్రూపులు & నగదు అవలోకనం',
      'expected': 'ఆశించిన',
      'collected': 'వసూలు చేసినవి',
      'pending': 'పెండింగ్',
      'chit_groups': 'చిట్ గ్రూపులు',
      'member_names': 'సభ్యుల పేర్లు',
      'member_names_hint': 'లైన్‌కు ఒకటి: పేరు, మొబైల్ (ఐచ్ఛికం)',
      'choose_date': 'తేదీని ఎంచుకోండి',
      'no_groups_configured': 'ఇంకా ఎలాంటి గ్రూపులు కాన్ఫిగర్ చేయబడలేదు.',
      'create_first_group': 'మీ మొదటి గ్రూప్ సృష్టించండి',
      'started': 'ప్రారంభించబడింది',
      'members': 'సభ్యులు',
      'monthly': 'నెలవారీ',
      'duration': 'వ్యవధి',
      'months': 'నెలలు',
      'sync': 'సమకాలీకరించు',
      'edit': 'సవరించు',
      'delete': 'తొలగించు',
      'pending_list': 'బకాయిల జాబితా',
      'monthly_report': 'నెలవారీ నివేదిక',
      'settings': 'సెట్టింగులు',
      'recent_activity': 'ఇటీవలి చర్యలు',
      'view_all': 'అన్నీ చూడండి',
      'no_activity_yet':
          'ఇంకా ఎలాంటి చర్య లేదు. ట్రాకింగ్ ప్రారంభించడానికి గ్రూప్ మరియు సభ్యులను జోడించండి.',
      'pending_dues': 'బకాయిలు',
      'all_dues_collected': 'ఈ నెలకు అన్ని బకాయిలు వసూలు చేయబడ్డాయి! 🎉',
      'overdue': 'గడువు దాటినవి',

      // Group Screen
      'group_name': 'గ్రూప్ పేరు',
      'installment_amt': 'నెలవారీ వాయిదా',
      'duration_months': 'వ్యవధి (నెలలు)',
      'start_date': 'ప్రారంభ తేదీ',
      'create_group_btn': 'గ్రూప్ సృష్టించండి',
      'group_list': 'క్రియాశీల గ్రూపులు',

      // Member Screen
      'member_name': 'సభ్యుడి పేరు',
      'father_name': 'తండ్రి పేరు',
      'mobile_number': 'మొబైల్ సంఖ్య',
      'address': 'చిరునామా',
      'aadhaar_optional': 'ఆధార్ సంఖ్య (ఐచ్ఛికం)',
      'profile_photo': 'ప్రొఫైల్ ఫోటో',
      'select_group': 'గ్రూప్ ఎంచుకోండి',
      'register_member_btn': 'సభ్యుడిని నమోదు చేయండి',
      'members_list': 'సభ్యుల జాబితా',
      'member_profile': 'సభ్యుని ప్రొఫైల్',
      'total_paid': 'మొత్తం చెల్లించారు',
      'pending_bal': 'పెండింగ్',
      'enrolled_groups': 'చేరిన సమూహాలు',
      'not_enrolled': 'ఏ సమూహంలోనూ చేరలేదు.',
      'months_unit': 'నెలలు',
      'month_unit': 'నెల',

      // Payment Screen
      'payments_tracker': 'చెల్లింపుల ట్రాకర్',
      'paid_status': 'చెల్లించారు',
      'pending_status': 'బకాయి ఉంది',
      'toggle_payment': 'మార్చడానికి నొక్కండి',
      'installment_history': 'వాయిదాల చరిత్ర',

      // Winner Screen
      'winner_module': 'వేలం విజేతలు',
      'declare_winner': 'నెలవారీ విజేతను ప్రకటించండి',
      'win_amount': 'విజేత బిడ్ మొత్తం',
      'select_winner': 'విజేతను ఎంచుకోండి',
      'winner_date': 'విజేత తేదీ',
      'winner_history': 'విజేతల చరిత్ర',
      'bid_amount': 'బిడ్ మొత్తం',

      // Pending List Screen
      'due_amount': 'బకాయి మొత్తం',
      'call_reminder': 'కాల్ చేయండి',
      'whatsapp_reminder': 'వాట్సాప్ రిమైండర్',

      // Settings Screen
      'dark_theme': 'డార్క్ థీమ్',
      'light_theme': 'లైట్ థీమ్',
      'language': 'భాష / Language / زبان',
      'backup_restore': 'బ్యాకప్ & పునరుద్ధరణ',
      'manual_backup': 'బ్యాకప్ ఎగుమతి చేయండి',
      'google_drive_backup': 'గూగుల్ డ్రైవ్ బ్యాకప్',
      'auto_local_backup': 'ఆటోమేటిక్ లోకల్ బ్యాకప్',
      'restore_backup': 'బ్యాకప్ పునరుద్ధరించండి',
      'backup_copied_clipboard': 'బ్యాకప్ క్లిప్‌బోర్డ్కు నకలు అయ్యింది!',
      'import_backup_title': 'బ్యాకప్ దిగుమతి చేయండి',
      'import_backup_hint': 'ఇక్కడ బ్యాకప్ JSON ని పేస్ట్ చేయండి...',
      'unable_to_open': 'లింక్ తెరవలేకపోయాం.',
      'theme_description': 'యాప్ లుక్ ను మార్చండి',
      'biometric_description': 'లాక్‌లను ఫింగర్‌ప్రింట్ ద్వారా ఓపెన్ చేయండి',
      'privacy_policy': 'గోప్యతా విధానం',
      'about_app': 'యాప్ గురించి',
      'google_translate': 'గూగుల్ అనువాదం',
      'restore': 'పునరుద్ధరించు',
      'backup_success': 'బ్యాకప్ విజయవంతంగా పూర్తయింది!',
      'restore_success': 'డేటాబేస్ విజయవంతంగా పునరుద్ధరించబడింది!',
      'restore_fail': 'పునరుద్ధరణ విఫలమైంది. డేటాను తనిఖీ చేయండి.',
      'auction_paid': 'వేలం చెల్లించబడింది',
      'auction_left': 'వేలం బకాయి',
      'foreman_commission': 'ఫోర్మాన్ కమిషన్',
      'dividends_distributed': 'డివిడెండ్ పంపిణీ చేయబడింది',
      'payment_mode_cash': 'నగదు',
      'payment_mode_upi': 'యూ పీ ఐ',
      'payment_mode_bank': 'బ్యాంక్ బదిలీ',
      'payment_mode_transfer': 'బదిలీ',
      'send_receipt': 'రసీదు పంపండి',
      'transfer_installment': 'వాయిదాను బదిలీ చేయండి',
      'transfer_from': 'నుండి బదిలీ చేయండి',
      'transfer_to': 'కు బదిలీ చేయండి',
      'mark_as_paid': 'చెల్లించినట్లు గుర్తించండి',
      'remind_pending': 'మిగిలిన సభ్యులను గుర్తు చేయండి',
    },
    'hi': {
      'onboarding_title_1': 'डैशबोर्ड अवलोकन',
      'onboarding_subtitle_1':
          'एक नज़र में अपनी संग्रह दक्षता, लंबित देय राशि और नीलामी स्थिति देखेंें।',
      'onboarding_title_2': 'स्वचालित संदेश सेवा',
      'onboarding_subtitle_2':
          'व्हाट्सएप के माध्यम से भुगतान रसीदें और अतिदेय अनुस्मारक स्वचालित रूप से भेजें।',
      'onboarding_title_3': 'बहु-भाषा समर्थन',
      'onboarding_subtitle_3':
          'ऐप की भाषा को तुरंत अपनी पसंद में बदलने के लिए अनुवाद आइकन पर टैप करें।',
      'onboarding_title_4': 'सूचित रहें',
      'onboarding_subtitle_4':
          'स्थानीय सूचनाएं सक्षम करने के लिए घंटी आइकन पर टैप करें और कभी भी भुगतान अपडेट न चूकें।',
      'skip': 'छोड़ें',
      'next': 'आगे',
      'get_started': 'शुरू करें',
      'app_title': 'SanghaSetu',
      'login_title': 'फिनटेक चिठ फंड',
      'enter_phone': 'मोबाइल नंबर दर्ज करें',
      'send_otp': 'ओटीपी भेजें',
      'verify_otp': 'ओटीपी सत्यापित करें',
      'enter_otp': '6-अंकीय ओटीपी दर्ज करें',
      'enter_pin': '4-अंकीय सुरक्षित पिन दर्ज करें',
      'setup_pin': '4-अंकीय सुरक्षित पिन सेट करें',
      'confirm_pin': 'अपने पिन की पुष्टि करें',
      'pin_error': 'गलत पिन, पुनः प्रयास करें',
      'biometric_login': 'फिंगरप्रिंट लॉगिन',
      'forgot_pin': 'पिन भूल गए?',
      'reset_pin': 'सुरक्षित पिन रीसेट करें',
      'login_btn': 'लॉग इन करें',
      'save_btn': 'सहेजें',
      'cancel_btn': 'रद्द करें',

      // Dashboard
      'dashboard': 'डैशबोर्ड',
      'total_groups': 'कुल समूह',
      'total_members': 'कुल सदस्य',
      'monthly_collection': 'मासिक संग्रह',
      'pending_amount': 'लंबित राशि',
      'pending_members': 'लंबित सदस्य',
      'quick_actions': 'त्वरित कार्रवाइयाँ',
      'add_group': 'समूह जोड़ें',
      'add_member': 'सदस्य जोड़ें',
      'target': 'लक्ष्य',
      'collected_label': 'एकत्रित',
      'groups_cash_overview': 'समूह और नकद अवलोकन',
      'expected': 'अपेक्षित',
      'collected': 'एकत्रित',
      'pending': 'लंबित',
      'chit_groups': 'चिट समूह',
      'member_names': 'सदस्यों के नाम',
      'member_names_hint': 'प्रति पंक्ति एक: नाम, मोबाइल (वैकल्पिक)',
      'choose_date': 'तारीख चुनें',
      'no_groups_configured': 'अभी तक कोई समूह कॉन्फ़िगर नहीं किया गया है।',
      'create_first_group': 'अपना पहला समूह बनाएं',
      'started': 'शुरू हुआ',
      'members': 'सदस्य',
      'monthly': 'मासिक',
      'duration': 'अवधि',
      'months': 'महीने',
      'sync': 'सिंक करें',
      'edit': 'संपादित करें',
      'delete': 'हटाएं',
      'pending_list': 'लंबित सूची',
      'monthly_report': 'मासिक रिपोर्ट',
      'settings': 'सेटिंग्स',
      'recent_activity': 'हाल की गतिविधि',
      'view_all': 'सभी देखें',
      'no_activity_yet':
          'अभी तक कोई गतिविधि नहीं है। ट्रैकिंग शुरू करने के लिए समूह, सदस्य और भुगतान जोड़ें।',
      'pending_dues': 'लंबित बकाया',
      'all_dues_collected': 'इस महीने के सभी बकाया एकत्र कर लिए गए हैं! 🎉',
      'overdue': 'अतिदेय',

      // Group Screen
      'group_name': 'समूह का नाम',
      'installment_amt': 'मासिक किस्त',
      'duration_months': 'अवधि (महीने)',
      'start_date': 'प्रारंभ तिथि',
      'create_group_btn': 'समूह बनाएं',
      'group_list': 'सक्रिय समूह',

      // Member Screen
      'member_name': 'सदस्य का नाम',
      'father_name': 'पिता का नाम',
      'mobile_number': 'मोबाइल नंबर',
      'address': 'आवासीय पता',
      'aadhaar_optional': 'आधार संख्या (वैकल्पिक)',
      'profile_photo': 'प्रोफ़ाइल फ़ोटो',
      'select_group': 'समूह चुनें',
      'register_member_btn': 'सदस्य पंजीकृत करें',
      'members_list': 'सदस्यों की सूची',
      'member_profile': 'सदस्य प्रोफ़ाइल',
      'total_paid': 'कुल भुगतान',
      'pending_bal': 'लंबित',
      'enrolled_groups': 'पंजीकृत समूह',
      'not_enrolled': 'किसी भी समूह में नामांकित नहीं है।',
      'months_unit': 'महीने',
      'month_unit': 'महीना',

      // Payment Screen
      'payments_tracker': 'भुगतान ट्रैकर',
      'paid_status': 'भुगतान किया गया',
      'pending_status': 'लंबित',
      'toggle_payment': 'भुगतान बदलने के लिए टैप करें',
      'installment_history': 'किस्त का इतिहास',

      // Winner Screen
      'winner_module': 'नीलामी विजेता',
      'declare_winner': 'महीने के विजेता की घोषणा करें',
      'win_amount': 'विजेता बोली राशि',
      'select_winner': 'विजेता सदस्य चुनें',
      'winner_date': 'विजेता की तिथि',
      'winner_history': 'विजेताओं का इतिहास',
      'bid_amount': 'बोली राशि',

      // Pending List Screen
      'due_amount': 'बकाया राशि',
      'call_reminder': 'सदस्य को कॉल करें',
      'whatsapp_reminder': 'व्हाट्सएप रिमाइंडर',

      // Settings Screen
      'dark_theme': 'डार्क थीम',
      'light_theme': 'लाइट थीम',
      'language': 'भाषा / Language / తెలుగు / زبان',
      'backup_restore': 'बैकअप और पुनर्स्थापना',
      'manual_backup': 'JSON बैकअप निर्यात करें',
      'google_drive_backup': 'गूगल ड्राइव बैकअप',
      'auto_local_backup': 'ऑटो लोकल बैकअप',
      'restore_backup': 'बैकअप आयात और पुनर्स्थापित करें',
      'backup_copied_clipboard': 'बैकअप क्लिपबोर्ड पर कॉपी हो गया!',
      'import_backup_title': 'बैकअप आयात करें',
      'import_backup_hint': 'यहाँ बैकअप JSON पेस्ट करें...',
      'unable_to_open': 'लिंक खोलने में असमर्थ।',
      'theme_description': 'ऐप का स्वरूप बदलें',
      'biometric_description': 'अनलॉक करने के लिए फिंगरप्रिंट का उपयोग करें',
      'privacy_policy': 'गोपनीयता नीति',
      'about_app': 'ऐप के बारे में',
      'google_translate': 'गूगल अनुवाद',
      'restore': 'पुनर्स्थापित करें',
      'backup_success': 'बैकअप सफलतापूर्वक निष्पादित किया गया!',
      'restore_success': 'डेटाबेस सफलतापूर्वक पुनर्स्थापित किया गया!',
      'restore_fail': 'पुनर्स्थापना विफल रही। JSON सत्यापित करें।',
      'auction_paid': 'नीलामी का भुगतान किया गया',
      'auction_left': 'नीलामी शेष',
      'foreman_commission': 'फोरमैन कमीशन',
      'dividends_distributed': 'लाभांश वितरित किया गया',
      'payment_mode_cash': 'नकद',
      'payment_mode_upi': 'यूपीआई',
      'payment_mode_bank': 'बैंक ट्रांसफर',
      'payment_mode_transfer': 'ट्रांसफर',
      'send_receipt': 'रसीद भेजें',
      'transfer_installment': 'किस्त ट्रांसफर करें',
      'transfer_from': 'से ट्रांसफर करें',
      'transfer_to': 'को ट्रांसफर करें',
      'mark_as_paid': 'भुगतान के रूप में चिह्नित करें',
      'remind_pending': 'बाकी सदस्यों को याद दिलाएं',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  // RTL checker helper
  bool get isRtl => locale.languageCode == 'ur';

  // Text Direction helper
  TextDirection get textDirection =>
      isRtl ? TextDirection.rtl : TextDirection.ltr;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ur', 'te', 'hi'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
