const PDFDocument = require('pdfkit');
const { isNonEmptyString } = require('../utils/validators');

// In-memory document storage: Map<documentId, { metadata, pdfBuffer }>
const documentStore = new Map();

/**
 * Generates unique document ID
 */
function generateDocumentId() {
  return `DOC-${Date.now()}-${Math.floor(1000 + Math.random() * 9000)}`;
}

/**
 * Creates PDF buffer using PDFKit.
 */
function createPdfBuffer(data) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', err => reject(err));

      // Header
      doc.rect(0, 0, doc.page.width, 80).fill('#0f2b48');
      doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold')
         .text('SchemeSetu', 50, 25);
      doc.fontSize(11).font('Helvetica')
         .text('National AI Government Scheme Facilitation Platform', 50, 52);

      doc.moveDown(4);
      doc.fillColor('#111827');

      // Title
      doc.fontSize(16).font('Helvetica-Bold')
         .text('Official Scheme Application Form', 50, 105, { align: 'center' });
      doc.fontSize(10).font('Helvetica-Oblique').fillColor('#4b5563')
         .text(`Smart India Hackathon 2026 | Document Reference: ${data.documentId}`, { align: 'center' });

      doc.moveDown(1.5);

      // Application Metadata Box
      const topY = 150;
      doc.rect(50, topY, 500, 75).strokeColor('#cbd5e1').stroke();
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#1e293b')
         .text('Application ID:', 60, topY + 12)
         .text('Generated On:', 60, topY + 32)
         .text('Scheme Applied:', 60, topY + 52);

      doc.font('Helvetica').fillColor('#334155')
         .text(data.applicationId || 'N/A', 170, topY + 12)
         .text(new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }), 170, topY + 32)
         .text(`${data.schemeName} (${data.schemeId})`, 170, topY + 52);

      // Section 1: Applicant Details
      const appY = 240;
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#0f2b48')
         .text('1. Applicant Information', 50, appY);

      doc.rect(50, appY + 20, 500, 90).strokeColor('#cbd5e1').stroke();
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#1e293b')
         .text('Applicant Name:', 60, appY + 30)
         .text('Contact Phone:', 60, appY + 55)
         .text('Address:', 60, appY + 80);

      doc.font('Helvetica').fillColor('#334155')
         .text(data.applicantName || 'N/A', 170, appY + 30)
         .text(data.applicantPhone || 'N/A', 170, appY + 55)
         .text(data.applicantAddress || 'N/A', 170, appY + 80);

      // Section 2: Application Parameters
      const paramY = 365;
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#0f2b48')
         .text('2. Enterprise & Proposal Summary', 50, paramY);

      doc.rect(50, paramY + 20, 500, 100).strokeColor('#cbd5e1').stroke();
      const appData = data.applicationData || {};
      let rowOffset = 0;
      const entries = Object.entries(appData).slice(0, 4);

      if (entries.length === 0) {
        doc.fontSize(10).font('Helvetica-Oblique').fillColor('#64748b')
           .text('Standard entrepreneur profile verification completed via SchemeSetu eligibility engine.', 60, paramY + 35);
      } else {
        for (const [k, v] of entries) {
          doc.fontSize(10).font('Helvetica-Bold').fillColor('#1e293b')
             .text(`${k}:`, 60, paramY + 30 + rowOffset);
          doc.font('Helvetica').fillColor('#334155')
             .text(String(v), 200, paramY + 30 + rowOffset);
          rowOffset += 20;
        }
      }

      // Declaration & Signature Box
      const signY = 500;
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#0f2b48')
         .text('3. Declaration & Verification', 50, signY);

      doc.fontSize(9).font('Helvetica').fillColor('#475569')
         .text('I hereby declare that all particulars provided in this application are true, correct, and complete to the best of my knowledge. I agree to abide by the terms and guidelines mandated under the scheme.', 50, signY + 20, { width: 500, align: 'justify' });

      doc.moveDown(4);
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#0f2b48')
         .text('Authorized Signatory / Applicant Signature', 300, signY + 110, { align: 'right' });
      doc.text('Date & Seal of Facilitation Agent', 50, signY + 110);

      // Footer
      doc.fontSize(8).font('Helvetica').fillColor('#94a3b8')
         .text('Generated by SchemeSetu AI Platform - Verified & Tamper-evident Digital Application Document', 50, 720, { align: 'center', width: 500 });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * POST /api/v1/documents/generate
 */
async function generateDocument(req, res, next) {
  try {
    const { applicationId, user = {}, scheme = {}, applicationData = {} } = req.body || {};

    const docId = generateDocumentId();
    const appId = applicationId || `APP-${Date.now()}`;
    const applicantName = user.name || user.applicantName || 'Scheme Applicant';
    const applicantPhone = user.phone || user.contact || 'N/A';
    const applicantAddress = user.address || user.location || 'N/A';
    const schemeId = scheme.id || scheme.schemeId || 'N/A';
    const schemeName = scheme.name || scheme.schemeName || 'Government Scheme';

    const pdfBuffer = await createPdfBuffer({
      documentId: docId,
      applicationId: appId,
      applicantName,
      applicantPhone,
      applicantAddress,
      schemeId,
      schemeName,
      applicationData
    });

    const docRecord = {
      documentId: docId,
      applicationId: appId,
      preview: {
        applicantName,
        schemeName,
        applicationId: appId
      },
      pdfBuffer,
      createdAt: new Date().toISOString()
    };

    documentStore.set(docId, docRecord);

    return res.status(201).json({
      success: true,
      documentId: docId,
      preview: {
        applicantName,
        schemeName,
        applicationId: appId
      },
      message: 'Application document generated successfully'
    });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/v1/documents/download/:docId
 */
function downloadDocument(req, res, next) {
  try {
    const { docId } = req.params;

    if (!docId || !documentStore.has(docId)) {
      return res.status(404).json({
        success: false,
        error: `Document with ID '${docId}' not found.`
      });
    }

    return res.status(200).json({
      success: true,
      documentId: docId,
      downloadUrl: `/api/v1/documents/file/${docId}`,
      message: 'Document ready for download'
    });
  } catch (err) {
    next(err);
  }
}

/**
 * GET /api/v1/documents/file/:docId
 * Streams the generated PDF binary directly.
 */
function streamDocumentFile(req, res, next) {
  try {
    const { docId } = req.params;

    if (!docId || !documentStore.has(docId)) {
      return res.status(404).json({
        success: false,
        error: `Document file for '${docId}' not found.`
      });
    }

    const docRecord = documentStore.get(docId);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename="SchemeSetu_Application_${docId}.pdf"`);
    res.setHeader('Content-Length', docRecord.pdfBuffer.length);

    return res.send(docRecord.pdfBuffer);
  } catch (err) {
    next(err);
  }
}

module.exports = {
  generateDocument,
  downloadDocument,
  streamDocumentFile
};
