import { api } from '../services/api';

/**
 * Generates and triggers download of a valid SchemeSetu Application Slip PDF
 * Filename format: SchemeSetu_Application_Slip_<APP_ID>.pdf
 */
export async function downloadApplicationSlipPdf(app, user = {}) {
  const filename = `SchemeSetu_Application_Slip_${app.id || 'APP-2026-8891'}.pdf`;
  const applicantName = user.name || 'Demo Applicant (Ramesh Kumar)';
  const applicantPhone = user.phone || '+91 98765 43210';
  const applicantLocation = user.state ? `${user.district || 'Hyderabad'}, ${user.state}` : 'Hyderabad, Telangana';

  try {
    // 1. Try server-side PDFKit document generator
    const res = await api.post('/documents/generate', {
      applicationId: app.id,
      scheme: {
        name: app.schemeName,
        id: app.schemeId || 'SCHEME-001'
      },
      user: {
        name: applicantName,
        phone: applicantPhone,
        address: applicantLocation
      },
      applicationData: {
        'Application Status': app.status || 'Under Review',
        'Submission Date': app.date || '2026-08-20',
        'Scheme Category': app.category || 'Citizen Welfare',
        'Benefit / Loan Amount': `₹${Number(app.loanAmount || 300000).toLocaleString('en-IN')}`,
        'Nodal Verification Branch': 'Nodal Lead District Center',
        'Document Checklist': 'Aadhaar e-KYC Verified, Bank DBT Linked'
      }
    });

    if (res && res.documentId) {
      const fileUrl = `/api/v1/documents/file/${res.documentId}`;
      const response = await fetch(fileUrl);
      if (response.ok) {
        const blob = await response.blob();
        triggerBlobDownload(blob, filename);
        return true;
      }
    }
  } catch (err) {
    console.warn("Backend PDF generation fallback:", err.message);
  }

  // 2. Client-side fallback PDF generator (Valid raw vector PDF format)
  generateClientSidePdf(app, applicantName, applicantPhone, applicantLocation, filename);
  return true;
}

function triggerBlobDownload(blob, filename) {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
}

/**
 * Valid standard client-side PDF document generator
 */
function generateClientSidePdf(app, applicantName, applicantPhone, applicantLocation, filename) {
  const dateStr = new Date().toLocaleDateString('en-IN');
  const pdfContent = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
5 0 obj
<< /Length 750 >>
stream
BT
/F1 20 Tf
50 780 Td
(SchemeSetu - Government Scheme Application Slip) Tj
/F1 10 Tf
0 -25 Td
(Smart India Hackathon 2026 | National Welfare Discovery Platform) Tj
0 -30 Td
(Application ID: ${app.id || 'APP-2026-8891'}) Tj
0 -20 Td
(Scheme Name: ${app.schemeName || 'Government Scheme'}) Tj
0 -20 Td
(Applicant Name: ${applicantName}) Tj
0 -20 Td
(Contact Phone: ${applicantPhone}) Tj
0 -20 Td
(Location: ${applicantLocation}) Tj
0 -20 Td
(Submission Date: ${app.date || dateStr}) Tj
0 -20 Td
(Current Status: ${app.status || 'Under Review'}) Tj
0 -20 Td
(Benefit / Loan Limit: Rs. ${(app.loanAmount || 300000).toLocaleString('en-IN')}) Tj
0 -30 Td
(Branch Note: ${app.remarks || 'Verification in progress at designated nodal branch.'}) Tj
0 -40 Td
(Declaration: Certified prototype record generated by SchemeSetu AI Platform.) Tj
0 -20 Td
(Date Generated: ${dateStr}) Tj
ET
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000224 00000 n 
0000000295 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
1100
%%EOF`;

  const blob = new Blob([pdfContent], { type: 'application/pdf' });
  triggerBlobDownload(blob, filename);
}
